name: Validar campos obligatorios

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  validar_campos:
    runs-on: ubuntu-latest

    steps:
      
      - name: Obtener número del Issue vinculado
        id: issue
        run: |
          ISSUE_NUMBER=$(echo "${{ github.event.pull_request.body }}" | grep -oE '#[0-9]+' | head -n1 | tr -d '#')
          if [ -z "$ISSUE_NUMBER" ]; then
            echo "No se encontró un issue vinculado en la descripción (usa 'Closes #123')"
            echo "::error::PR sin Issue vinculado."
            exit 1
          fi
          echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_ENV

      - name: Obtener node_id del Issue
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUMBER} \
            > issue.json

          echo "NODE_ID=$(jq -r '.node_id' issue.json)" >> $GITHUB_ENV

      - name: Consultar campos del proyecto (GraphQL)
        run: |
          QUERY='{
            "query": "query { node(id: \"'$NODE_ID'\") { ... on Issue { projectItems(first: 10) { nodes { fieldValues(first: 10) { nodes { field { name } ... on ProjectV2ItemFieldNumberValue { number } ... on ProjectV2ItemFieldTextValue { text } } } } } } } }"
          }'
          echo "$QUERY" > query.json

          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d @query.json https://api.github.com/graphql > response.json

      - name: Validar campos obligatorios
        run: |
          HORAS=$(jq -r '.data.node.projectItems.nodes[0].fieldValues.nodes[] | select(.field.name=="Horas") | .number' response.json)
          CASOLA=$(jq -r '.data.node.projectItems.nodes[0].fieldValues.nodes[] | select(.field.name=="CasoLA") | .text' response.json)

          if [ -z "$HORAS" ] || [ "$HORAS" == "null" ]; then
            echo "::error::El campo 'Horas' es obligatorio pero está vacío o no definido."
            exit 1
          fi

          if [ -z "$CASOLA" ] || [ "$CASOLA" == "null" ]; then
            echo "::error::El campo 'CasoLA' es obligatorio pero está vacío o no definido."
            exit 1
          fi

          echo "Validación exitosa: Campos presentes ✔️"