name: Validar campos obligatorios

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  validar_campos:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener número del Issue vinculado
        id: issue
        run: |
          ISSUE_NUMBER=$(echo "${{ github.event.pull_request.body }}" | grep -oE '#[0-9]+' | head -n1 | tr -d '#')
          echo "Número de Issue detectado: $ISSUE_NUMBER"
          if [ -z "$ISSUE_NUMBER" ]; then
            echo "No se encontró un issue vinculado en la descripción (usa 'Closes #123')"
            echo "::error::PR sin Issue vinculado."
            exit 1
          fi
          echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_ENV

      - name: Obtener node_id del Issue
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUMBER} \
            > issue.json
          NODE_ID=$(jq -r '.node_id' issue.json)
          echo "Node ID del Issue: $NODE_ID"
          echo "NODE_ID=$NODE_ID" >> $GITHUB_ENV

      - name: Consultar campos del proyecto (GraphQL)
        run: |
          QUERY='{
            "query": "query { node(id: \"'$NODE_ID'\") { ... on Issue { projectItems(first: 10) { nodes { fieldValues(first: 10) { nodes { ... on ProjectV2ItemFieldNumberValue { number field { ... on ProjectV2FieldCommon { name } } } ... on ProjectV2ItemFieldTextValue { text field { ... on ProjectV2FieldCommon { name } } } ... on ProjectV2ItemFieldSingleSelectValue { name field { ... on ProjectV2FieldCommon { name } } } } } } } } } }"
          }'
          echo "Consulta GraphQL generada:"
          echo "$QUERY"
          echo "$QUERY" > query.json

          curl -s -H "Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d @query.json https://api.github.com/graphql > response.json

      - name: Mostrar respuesta GraphQL
        run: |
          echo "Respuesta GraphQL:"
          cat response.json

      - name: Validar campos obligatorios
        run: |
          echo "Número de Issue: $ISSUE_NUMBER"
          echo "Node ID: $NODE_ID"

          PROJECT_ITEMS=$(jq '.data.node.projectItems.nodes | length' response.json)
          echo "Cantidad de proyectos vinculados: $PROJECT_ITEMS"

          if [ "$PROJECT_ITEMS" -eq 0 ]; then
            echo "::error::El Issue no está vinculado a ningún proyecto v2. Por favor, asígnalo antes de continuar."
            exit 1
          fi

          HORAS=$(jq -r '.data.node.projectItems.nodes[0].fieldValues.nodes[] | select(.field.name=="Horas") | .number' response.json)
          CASOLA=$(jq -r '.data.node.projectItems.nodes[0].fieldValues.nodes[] | select(.field.name=="CasoLA") | .number' response.json)
          echo "Valor del campo Horas: $HORAS"
          echo "Valor del campo CasoLA: $CASOLA"

          if [ -z "$HORAS" ] || [ "$HORAS" == "null" ]; then
            echo "::error::El campo 'Horas' es obligatorio pero está vacío o no definido."
            exit 1
          fi

          if [ -z "$CASOLA" ] || [ "$CASOLA" == "null" ]; then
            echo "::error::El campo 'CasoLA' es obligatorio pero está vacío o no definido."
            exit 1
          fi

          echo "Validación exitosa: Campos presentes ✔️"